version: '3'

services:
  first_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8081
    environment:
      - DOMAIN_NAME=example1.com
    ports:
      - "8081:8081"

  second_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8082
    environment:
      - DOMAIN_NAME=example2.com
    ports:
      - "8082:8082"

  third_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8083
    environment:
      - DOMAIN_NAME=example3.com
    ports:
      - "8083:8083"

  fourth_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8084
    environment:
      - DOMAIN_NAME=example4.com
    ports:
      - "8084:8084"

  fifth_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8085
    environment:
      - DOMAIN_NAME=example5.com
    ports:
      - "8085:8085"

  sixth_site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8086
    environment:
      - DOMAIN_NAME=example6.com
    ports:
      - "8086:8086"
