# Використовуємо офіційний образ Nginx з підтримкою динамічного розподілу трафіку
FROM nginx:latest

# Копіюємо конфігураційний файл в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

# Відкриваємо порт 80
EXPOSE 80

# Запускаємо Nginx в фоновому режимі
CMD ["nginx", "-g", "daemon off;"]
